# Generated by Django 2.1.7 on 2021-09-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiachroGroup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fasttextdiachro',
            name='methode_clustering',
            field=models.CharField(choices=[('saut maximal', 'saut maximal'), ('saut moyen', 'saut moyen')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='glovediachro',
            name='methode_clustering',
            field=models.CharField(choices=[('saut maximal', 'saut maximal'), ('saut moyen', 'saut moyen')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='word2vecdiachro',
            name='methode_clustering',
            field=models.CharField(choices=[('saut maximal', 'saut maximal'), ('saut moyen', 'saut moyen')], default=None, max_length=100),
        ),
    ]
