# Generated by Django 2.1.7 on 2021-04-15 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DelimitCorpus', '0003_auto_20210415_2045'),
        ('AmeliorText', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allexceptadd',
            name='DocTransformeRef',
        ),
        migrations.RemoveField(
            model_name='allexceptremove',
            name='DocTransformeRef',
        ),
        migrations.RemoveField(
            model_name='docremove',
            name='DocTransformeRef',
        ),
        migrations.AddField(
            model_name='allexceptadd',
            name='DocExtractRef',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='DelimitCorpus.DocExtractInitial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allexceptremove',
            name='DocExtractRef',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='DelimitCorpus.DocExtractInitial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docremove',
            name='DocExtractRef',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='DelimitCorpus.DocExtractInitial'),
            preserve_default=False,
        ),
    ]
