# Generated by Django 2.1.7 on 2021-04-15 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=20)),
                ('idpersee', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CorpusEtude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('user_restrict', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=80)),
                ('revue', models.CharField(max_length=50)),
                ('stopworddossier', models.CharField(max_length=500)),
                ('typedoc', models.CharField(max_length=400)),
                ('datemin', models.IntegerField()),
                ('datemax', models.IntegerField()),
                ('langue', models.CharField(max_length=300)),
                ('motmin', models.IntegerField()),
                ('pagemin', models.IntegerField()),
                ('typecatnon', models.TextField()),
                ('comment', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='DocReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=550)),
                ('url', models.CharField(max_length=250)),
                ('TextRef', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=80)),
                ('annee', models.IntegerField()),
                ('AuteursRef', models.ManyToManyField(to='DelimitCorpus.Auteur')),
            ],
        ),
        migrations.CreateModel(
            name='DocTransforme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TextTransforme', models.CharField(max_length=150)),
                ('CorpusEtudeRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DelimitCorpus.CorpusEtude')),
                ('DocReferenceRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DelimitCorpus.DocReference')),
            ],
        ),
        migrations.CreateModel(
            name='Revue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('nompersee', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=80)),
                ('IndexDeb', models.IntegerField()),
                ('IndexFin', models.IntegerField()),
                ('TextField', models.TextField()),
                ('comment', models.CharField(max_length=250)),
                ('DocTransformeRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DelimitCorpus.DocTransforme')),
            ],
        ),
        migrations.AddField(
            model_name='docreference',
            name='RevueRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DelimitCorpus.Revue'),
        ),
    ]
