# Generated by Django 2.1.7 on 2021-04-15 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DelimitCorpus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocExtractInitial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TextExtract', models.CharField(max_length=150)),
                ('CorpusEtudeRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DelimitCorpus.CorpusEtude')),
                ('DocReferenceRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DelimitCorpus.DocReference')),
            ],
        ),
        migrations.RemoveField(
            model_name='doctransforme',
            name='DocReferenceRef',
        ),
        migrations.AddField(
            model_name='doctransforme',
            name='DocExtractRef',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='DelimitCorpus.DocExtractInitial'),
            preserve_default=False,
        ),
    ]
