# Generated by Django 2.1.7 on 2021-04-16 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DelimitCorpus', '0003_auto_20210415_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyntheseTransform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seuilTitre', models.FloatField()),
                ('SupprSlashSecondPart', models.BooleanField()),
                ('SupprBeforeTitre', models.BooleanField()),
                ('motsResume', models.TextField(max_length=400)),
                ('zoneResume', models.PositiveIntegerField()),
                ('AjoutResumeFr', models.BooleanField()),
                ('motstMotCle', models.TextField(max_length=400)),
                ('zonetMotCle', models.PositiveIntegerField()),
                ('AjoutMotCleFr', models.BooleanField()),
                ('seuilgeoHtdePage', models.PositiveIntegerField()),
                ('seuilspgeoHtdePage', models.PositiveIntegerField()),
                ('SupprNoteBio', models.BooleanField()),
                ('SupprNoteEdito', models.BooleanField()),
                ('SupprNoteBasDePage', models.BooleanField()),
                ('SupprBilioEtFin', models.BooleanField()),
                ('motsBiblio', models.TextField(max_length=400)),
                ('zoneBiblio', models.PositiveIntegerField()),
                ('supprAppendix', models.BooleanField()),
                ('motsAppendix', models.TextField(max_length=400)),
                ('zoneAppendix', models.PositiveIntegerField()),
                ('remplaceSsTitre', models.BooleanField()),
                ('EssaiHomogeneTitre', models.BooleanField()),
                ('motsFigure', models.TextField(max_length=600)),
                ('ContenuCentreRemove', models.BooleanField()),
                ('motsFinDoc', models.TextField(max_length=600)),
                ('ManuscritRemove', models.BooleanField()),
                ('litigecedille', models.BooleanField()),
                ('FinMotTrait', models.BooleanField()),
                ('FinLigneNormalise', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='corpusetude',
            name='extract_mot',
            field=models.CharField(choices=[('FromTEIDocMot', 'FromTEIDocMot')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corpusetude',
            name='SyntheseTransformRef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DelimitCorpus.SyntheseTransform'),
        ),
    ]
