# Generated by Django 2.1.7 on 2021-04-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DelimitCorpus', '0005_auto_20210416_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='synthesetransform',
            name='AllExceptAddRef',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='synthesetransform',
            name='AllExceptRemoveRef',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='synthesetransform',
            name='DocRemoveRef',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
