# Generated by Django 2.1.7 on 2021-04-15 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FinaliseCorpus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountOcc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomresult', models.CharField(max_length=200, unique=True)),
                ('mode', models.CharField(max_length=50)),
                ('terme', models.CharField(default=None, max_length=300)),
                ('revue', models.CharField(choices=[('Annales,Espace', 'Annales,Espace'), ('Annales', 'Annales'), ('Espace', 'Espace')], max_length=100)),
                ('epoque', models.CharField(max_length=300)),
                ('user_restrict', models.CharField(max_length=50)),
                ('CorpusFinRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinaliseCorpus.CorpusFin')),
            ],
        ),
    ]
