# Generated by Django 2.1.7 on 2021-09-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cluster', '0002_auto_20210930_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fasttextrcluster',
            name='methode_clustering',
            field=models.CharField(choices=[('Kmeans', 'Kmeans'), ('saut moyen', 'saut moyen'), ('saut minimal', 'saut minimal'), ('saut maximal', 'saut maximal')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='glovercluster',
            name='methode_clustering',
            field=models.CharField(choices=[('Kmeans', 'Kmeans'), ('saut moyen', 'saut moyen'), ('saut minimal', 'saut minimal'), ('saut maximal', 'saut maximal')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='word2vecrcluster',
            name='methode_clustering',
            field=models.CharField(choices=[('Kmeans', 'Kmeans'), ('saut moyen', 'saut moyen'), ('saut minimal', 'saut minimal'), ('saut maximal', 'saut maximal')], default=None, max_length=100),
        ),
    ]
